# 整合nacos，如果不想用nacos，可以把/nacos目录下的配置文件拷贝到/resources目录下替换使用
spring:
  config:
    import:
      - optional:nacos:user_config.yml
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        namespace: e67a68d9-0db1-4699-8dd2-522e9022ac45
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: e67a68d9-0db1-4699-8dd2-522e9022ac45
rocketmq:
  producer:
    group: cluster-group
    send-message-timeout: 10000
  name-server: 192.168.204.81:9876:9876
