# 整合nacos，如果不想用nacos，可以把/nacos目录下的配置文件拷贝到/resources目录下替换使用
spring:
  config:
    import:
      - optional:nacos:gateway_config.yml
      - optional:nacos:gateway_routes.yml
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        namespace: 83b65d75-e9bc-4037-9b98-44506f7f3aa2
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: 83b65d75-e9bc-4037-9b98-44506f7f3aa2
    gateway:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: 83b65d75-e9bc-4037-9b98-44506f7f3aa2
        locator:
          enabled: true

