spring:
  profiles:
    active: dev
  application:
    name: mall-coupon-new

# mybaits-plus配置
mybatis-plus:
  # MyBatis Mapper所对应的XML文件位置
  mapper-locations: classpath*:/mapper/*Mapper.xml
  global-config:
    # 关闭MP3.0自带的banner
    banner: false
    db-config:
      # 主键类型 0:数据库ID自增 1.未定义 2.用户输入 3 id_worker 4.uuid 5.id_worker字符串表示
      id-type: AUTO
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: NOT_NULL
      # 默认数据库表下划线命名
      table-underline: true

management:
  server:
    add-application-context-header: false
  metrics:
    export:
      prometheus:
        enabled: true
      jmx:
        enabled: true
#        springboot监控插件Actuator
  endpoints:
#    暴露某个端点
    web:
      exposure:
        include: '*'
#        # 显示health详细信息
  endpoint:
    health:
      show-details: always
  health:
    redis:
      enabled: true
