# 整合nacos，如果不想用nacos，可以把/nacos目录下的配置文件拷贝到/resources目录下替换使用
spring:
  config:
    import:
      - optional:nacos:new_coupon_config.yml
  cloud:
    nacos:
      config:
        server-addr: 192.168.204.81:8848
        namespace: 4da593c3-13a6-4194-9b19-45f4bffcdfd5
#        192.168.204.81
      discovery:
        server-addr: 192.168.204.81:8848
        namespace: 4da593c3-13a6-4194-9b19-45f4bffcdfd5
logging:
  level:
    com.swp.feign: debug

feign:
  client:
    config:
      mall-coupon: # 对应服务
        connect-timeout: 5000
        read-timeout: 10000
  hystrix:
    enabled: true # 开启hystrix断路器

